---
title: "ecological_analyses"
output: 
  html_document: default
params:
  directory: "~/Metares/pipeline/test_rapport_avec_R"
  threshold_best_abundance: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(stringr)
library(dplyr)
library(ggplot2)
library(viridis)
library(cowplot)
library(vegan)
```

```{r open_data, include=FALSE}
setwd(params$directory)

#Take all the metaphlan file
file_list <- readLines("file_path_metaphlan.txt")

open_and_merge_dataframe <- function(file, dataframe) {
  data <- read.table(file,sep='\t',header=F,dec='.')
  data <- data[c(1,3)]
  colnames(data) <- c("clade_name", "relative_abundance")
  as.numeric(data$relative_abundance)
  
  #Extract sample name from the file name
  split_sample_name <- strsplit(file, "_")[[1]]
  sample <- paste(split_sample_name[c(-length(split_sample_name) + 1, -length(split_sample_name))],collapse='_')
  
  #Remove Archaea from table and take only column 1 and 3
  data <- data[!grepl("k__Archaea", data$clade_name),]
  #Take only genus
  data <- data[grep("g__", data$clade_name),]
  datagenus <- data[!grepl("s__", data$clade_name),]
  #Rename genus
  datagenus$clade_name <- substr(str_split_i(datagenus$clade_name,'\\|',-1),4,nchar(str_split_i(datagenus$clade_name,'\\|',-1)))
  colnames(datagenus) <- c("clade_name",sample)
  
  dataframegenus <- merge(datagenus,dataframe,by="clade_name",all=T)
  return(dataframegenus)
}

#Create first dataframe empty
columns = c("clade_name") 
datagenus = data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(datagenus) = columns

#Merge all the file
for (file in file_list) {
  datagenus <- open_and_merge_dataframe(file, datagenus)
}

rownames(datagenus) <- datagenus[,1]
datagenus[,1] <- NULL

name_sample <- colnames(datagenus)
```

## Composition of bacterial populations

```{r bargraph, echo=FALSE}
#Function for each column to extract genus with best abundance.
genus_best_abundance <- rownames(filter(datagenus, if_any(everything(),  ~ .x > params$threshold_best_abundance)))

if (ncol(datagenus) >  1)
{
  datagenus_best_abundance <- datagenus[(row.names(datagenus) %in% genus_best_abundance),]
  datagenus_worst_abundance <- datagenus[!(row.names(datagenus) %in% genus_best_abundance),]
} else if (ncol(datagenus) == 1)
{
  datagenus_best_abundance <- datagenus[row.names(datagenus) %in% genus_best_abundance,]
  datagenus_best_abundance <- data.frame(datagenus_best_abundance, row.names = genus_best_abundance)
  colnames(datagenus_best_abundance) <- colnames(datagenus)
  
  genus_worst_abundance <- rownames(filter(datagenus, !(row.names(datagenus) %in% genus_best_abundance)))
  datagenus_worst_abundance <- datagenus[!(row.names(datagenus) %in% genus_best_abundance),]
  datagenus_worst_abundance <- data.frame(datagenus_worst_abundance, row.names = genus_worst_abundance)
  colnames(datagenus_worst_abundance) <- colnames(datagenus)
}

#Sum columns from dataframe with worst abundance

datagenus_best_abundance[c("Others"),] <- rbind(colSums(datagenus_worst_abundance, na.rm = TRUE))

#Make the histogram
reverse_datagenus_best_abundance <- t(datagenus_best_abundance)
#Recreate a good dataframe for the bar graph
dfbargraph <- data.frame(
  "Sample" = rep(name_sample,each=ncol(reverse_datagenus_best_abundance)),
  "Abundance" = Reduce(c, c(datagenus_best_abundance)),
  "Genus" = rep(colnames(reverse_datagenus_best_abundance),times=ncol(datagenus_best_abundance))
)
dfbargraph$Genus <- factor(dfbargraph$Genus, levels=colnames(reverse_datagenus_best_abundance))
b <- ggplot(dfbargraph, aes(fill=Genus, y=Abundance, x=Sample)) + 
  geom_bar(position="fill", stat="identity")
b

```


## ecological analyses

Alpha factor

```{r ecological_analyses, echo=FALSE}

#dataframe processing.
reverse_datagenus <- t(datagenus)
reverse_datagenus[is.na(reverse_datagenus)] = 0

sample <- rownames(reverse_datagenus)

#alpha factor processing
H <- diversity(reverse_datagenus)
richness <- specnumber(reverse_datagenus)

alpha <- cbind.data.frame(shannon = H, richness = richness, sample = sample)

plot.shan <- ggplot(alpha, aes(x = sample, y = shannon, colour = sample)) +
  geom_point(size = 3) +
  scale_colour_viridis_d(option = "magma", begin = 0.2, end = 0.8) +
  ylab("Shannon index") + 
  xlab("") +
  theme_bw() +
  theme(axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_line(colour = "black"),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 12))
plot.rich <-ggplot(alpha, aes(x = sample, y = richness, colour = sample)) +
  geom_point(size = 3) +
  scale_colour_viridis_d(option = "magma", begin = 0.2, end = 0.8) +
  ylab("Species Richness") +
  xlab("") +
  theme_bw() +
  theme(axis.title.y = element_text(size = 15),
        axis.title.x = element_text(size = 15),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        plot.title = element_text(hjust = 0.5),
        axis.line = element_line(colour = "black"),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 12))
legend <- get_legend(plot.rich)

plot_grid(plot.shan + theme(legend.position = "none"), plot.rich + theme(legend.position = "none"),ncol = 2)
```

